version: '3.8'

services:
  telegraf:
    image: telegraf:1.32.1
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf  # Mount the Telegraf config
      - ./logs:/var/log/telegraf  # Mount the host directory to store logs